module.exports = {
  ENDPOINT_CONTRACTS: true,
  ENDPOINT_REVISES: true,
  ENDPOINT_START_AND_FINISH_CONTRACTS: true,
  ENDPOINT_PAYMENTS_CALENDAR: true,
  ENDPOINT_REPORTS: true,
  ENDPOINT_SUMMARY_REPORTS: true,
};
